projects_dir = "/home/tsrt/Documents/MOOC.fi"
"closed-exercises-for:mooc-programming-25" = [
    "part04-01_hello_visual_studio_code",
    "part04-02_line",
    "part04-03_box_of_hashes",
    "part04-04_square_of_hashes",
    "part04-05_square",
    "part04-06_triangle",
    "part04-07_shape",
    "part04-08_spruce",
    "part04-09_greatest_number",
    "part04-10_same_characters",
    "part04-11_first_second_last",
    "part04-12_change_value_of_item",
    "part04-13_add_items_to_list",
    "part04-14_addition_and_removal",
    "part04-15_same_word_twice",
    "part04-16_list_twice",
    "part04-17_length_of_list",
    "part04-18_mean",
    "part04-19_range_of_list",
    "part04-20_star_studded",
    "part04-21_negative_to_positive",
    "part04-22_list_of_stars",
    "part04-23_anagrams",
    "part04-24_palindromes",
    "part04-25_sum_of_positives",
    "part04-26_even_numbers",
    "part04-27_sum_of_lists",
    "part04-28_distinct_numbers",
    "part04-29_length_of_longest",
    "part04-30_shortest_in_list",
    "part04-31_all_longest_in_list",
    "part04-32_integers_to_strings",
    "part04-33_everything_reversed",
    "part04-34_most_common_character",
    "part04-35_no_vowels_allowed",
    "part04-36_no_shouting_allowed",
    "part04-37_neighbours_in_list",
    "part04-38_grade_statistics",
    "part05-01_longest_string",
    "part05-02_number_of_elements",
    "part05-03_go",
    "part05-04_sudoku_row",
    "part05-05_sudoku_column",
    "part05-06_sudoku_block",
    "part05-07_sudoku_grid",
    "part05-08_items_multiplied_by_two",
    "part05-09_remove_smallest",
    "part05-10_sudoku_print_and_add",
    "part05-11_sudoku_add_to_copy",
    "part05-12_tic_tac_toe",
    "part05-13_transpose_matrix",
    "part05-14_times_ten",
    "part05-15_factorials",
    "part05-16_histogram",
    "part05-17_phone_book_v1",
    "part05-18_phone_book_v2",
    "part05-19_invert_dictionary",
    "part05-20_numbers_spelled_out",
    "part05-21_movie_database",
    "part05-22_find_movies",
    "part05-23_create_tuple",
    "part05-24_oldest_person",
    "part05-25_older_people",
    "part05-26_student_database",
    "part05-27_letter_square",
    "part06-01_largest_number",
    "part06-02_fruit_market",
    "part06-03_matrix",
    "part06-04_course_grading_part_1",
    "part06-05_course_grading_part_2",
    "part06-06_course_grading_part_3",
    "part06-07_spellchecker",
    "part06-08_recipe_search",
    "part06-09_city_bikes",
    "part06-10_inscription",
    "part06-11_diary",
    "part06-12_filtering_file_contents",
    "part06-13_store_personal_data",
    "part06-14_course_grading_part_4",
    "part06-15_word_search",
    "part06-16_dictionary_file",
    "part06-17_read_input",
    "part06-18_parameter_validation",
    "part06-19_incorrect_lottery_numbers",
    "part07-01_hypotenuse",
    "part07-02_special_characters",
    "part07-03_fractions",
    "part07-04_lottery_numbers",
    "part07-05_password_generator_part_1",
    "part07-06_password_generator_part_2",
    "part07-07_dice_roller",
    "part07-08_random_words",
    "part07-09_how_old",
    "part07-10_valid_pic",
    "part07-11_screen_time",
    "part07-12_json_files",
    "part07-13_course_statistics",
    "part07-14_who_cheated",
    "part07-15_who_cheated_2",
    "part07-16_spellchecker_2",
    "part07-17_string_helper",
    "part07-18_own_programming_language",
]
